name: Run Tests and Upload Coverage

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci --force

      - name: Run type check
        run: npm run type:check

      - name: Run lint ts
        run: npm run lint:ts

      - name: Run tests
        run: npm run test:coverage

      - name: Upload Coverage to Codecov
        if: ${{ github.event_name == 'pull_request' }}
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./.tests/coverage/lcov.info
          flags: unittests
