name: Test and build

on:
  push:
    branches:
      - master
      - develop

  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci --force

      - name: Run type check
        run: npm run type:check

      - name: Run lint ts
        run: npm run lint:ts

      - name: Run tests
        run: npm run test:coverage

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./.tests/coverage/lcov.info
          flags: unittests
          fail_ci_if_error: true

  build:
    needs: test
    if: ${{ success() }}
    runs-on: ubuntu-latest

    steps:
      - name: Debug build
        run: |
          echo "build step"
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Commit built files
        if: ${{ github.ref == 'refs/heads/develop' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add dist
          git commit -m "Build files from latest commit" || echo "No changes to commit"
          git push origin develop
